# ***Libraries used***

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# ***File loading***

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
path = "/content/drive/MyDrive/MLprojectself/Heart disease data.csv"

In [4]:
org_df = pd.read_csv(path)

In [5]:
org_df.shape

(40000, 45)

# ***Data cleaning***

In [6]:
df = org_df.copy()

In [7]:
df.head()  #viewing first few rows of the data

,Patient_ID,Age,Gender,Height_cm,Weight_kg,BMI,Waist_cm,Smoking,Alcohol,PhysicalActivity,...,Oldpeak,STSlope,DailySteps,HRV,WearableECGAlerts,MedicationAdherence,RemoteMonitoringFreq,AQIExposure,AvgTempExposure,HeartDisease
0,1,66,Male,175,86,28.1,73,0,0,0,...,0.9,1,14313,73,4,84,3,167,26.8,0
1,2,48,Male,187,81,23.2,119,0,1,3,...,1.0,1,15246,97,2,57,16,224,14.9,0
2,3,68,Male,181,71,21.7,123,1,0,0,...,1.2,1,11572,41,3,81,1,121,33.0,0
3,4,41,Male,175,70,22.9,110,0,1,1,...,1.4,0,8243,108,1,79,28,296,21.8,0
4,5,76,Female,156,75,30.8,78,0,0,4,...,1.2,0,13219,34,15,79,15,257,19.4,0

In [8]:

df.tail() #reviewing last few rows of the data

,Patient_ID,Age,Gender,Height_cm,Weight_kg,BMI,Waist_cm,Smoking,Alcohol,PhysicalActivity,...,Oldpeak,STSlope,DailySteps,HRV,WearableECGAlerts,MedicationAdherence,RemoteMonitoringFreq,AQIExposure,AvgTempExposure,HeartDisease
39995,39996,87,Male,186,117,33.8,112,1,0,0,...,2.0,1,5879,45,12,90,17,217,35.7,1
39996,39997,90,Female,153,112,47.8,102,0,1,3,...,3.4,1,672,61,7,92,23,160,23.3,1
39997,39998,28,Female,177,70,22.3,66,0,1,2,...,3.9,1,4377,57,1,61,15,109,24.5,1
39998,39999,61,Male,152,98,42.4,70,1,0,1,...,4.6,0,1385,57,7,79,9,115,12.1,1
39999,40000,38,Male,177,88,28.1,108,1,0,3,...,3.9,1,3527,68,0,59,27,279,26.6,1

In [9]:
data_types = df.dtypes
data_types.to_csv('data_types.csv') # reviewing the data types

In [10]:
info = df.info() #information about data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 45 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Patient_ID            40000 non-null  int64
 1   Age                   40000 non-null  int64
 2   Gender                40000 non-null  object
 3   Height_cm             40000 non-null  int64
 4   Weight_kg             40000 non-null  int64
 5   BMI                   40000 non-null  float64
 6   Waist_cm              40000 non-null  int64
 7   Smoking               40000 non-null  int64
 8   Alcohol               40000 non-null  int64
 9   PhysicalActivity      40000 non-null  int64
 10  DietScore             40000 non-null  int64
 11  SleepHours            40000 non-null  float64
 12  StressLevel           40000 non-null  int64
 13  FamilyHistory         40000 non-null  int64
 14  Diabetes              40000 non-null  int64
 15  Hypertension          40000 non-null  int64
 16  KidneyDisease         40000 non-null  int64
 17  StrokeHistory         40000 non-null  int64
 18  SystolicBP            40000 non-null  int64
 19  DiastolicBP           40000 non-null  int64
 20  RestingHR             40000 non-null  int64
 21  RespRate              40000 non-null  int64
 22  BodyTemp_C            40000 non-null  float64
 23  SpO2                  40000 non-null  int64
 24  TotalChol             40000 non-null  int64
 25  HDL                   40000 non-null  int64
 26  LDL                   40000 non-null  int64
 27  Triglycerides         40000 non-null  int64
 28  FBS                   40000 non-null  int64
 29  HbA1c                 40000 non-null  float64
 30  Creatinine            40000 non-null  float64
 31  RestingECG            40000 non-null  int64
 32  ChestPainType         40000 non-null  int64
 33  ExerciseAngina        40000 non-null  int64
 34  MaxHR                 40000 non-null  int64
 35  Oldpeak               40000 non-null  float64
 36  STSlope               40000 non-null  int64
 37  DailySteps            40000 non-null  int64
 38  HRV                   40000 non-null  int64
 39  WearableECGAlerts     40000 non-null  int64
 40  MedicationAdherence   40000 non-null  int64
 41  RemoteMonitoringFreq  40000 non-null  int64
 42  AQIExposure           40000 non-null  int64
 43  AvgTempExposure       40000 non-null  float64
 44  HeartDisease          40000 non-null  int64
dtypes: float64(7), int64(37), object(1)
memory usage: 13.7+ MB

By viewing the output of the data info, it is concluded that there is no missing value. For further confirmation we cross check.

In [11]:
df.isnull().sum().sum()

np.int64(0)

In [12]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Patient_ID,40000.0,NaN,NaN,NaN,20000.5,11547.14972,1.0,10000.75,20000.5,30000.25,40000.0
Age,40000.0,NaN,NaN,NaN,57.43485,19.105534,25.0,41.0,58.0,74.0,90.0
Gender,40000,2,Female,20101,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Height_cm,40000.0,NaN,NaN,NaN,169.991425,11.794922,150.0,160.0,170.0,180.0,190.0
Weight_kg,40000.0,NaN,NaN,NaN,79.959425,19.321428,45.0,66.0,79.0,92.0,120.0
BMI,40000.0,NaN,NaN,NaN,28.082963,7.914967,12.5,22.1,27.2,33.2,53.3
Waist_cm,40000.0,NaN,NaN,NaN,97.389,19.045755,65.0,81.0,97.0,114.0,130.0
Smoking,40000.0,NaN,NaN,NaN,0.4135,0.492467,0.0,0.0,0.0,1.0,1.0
Alcohol,40000.0,NaN,NaN,NaN,0.500025,0.500006,0.0,0.0,1.0,1.0,1.0
PhysicalActivity,40000.0,NaN,NaN,NaN,1.990375,1.413305,0.0,1.0,2.0,3.0,4.0
DietScore,40000.0,NaN,NaN,NaN,5.47985,2.878628,1.0,3.0,5.0,8.0,10.0
SleepHours,40000.0,NaN,NaN,NaN,7.005315,1.15459,5.0,6.0,7.0,8.0,9.0
StressLevel,40000.0,NaN,NaN,NaN,5.482125,2.887999,1.0,3.0,5.0,8.0,10.0
FamilyHistory,40000.0,NaN,NaN,NaN,0.585575,0.492629,0.0,0.0,1.0,1.0,1.0
Diabetes,40000.0,NaN,NaN,NaN,0.333575,0.471496,0.0,0.0,0.0,1.0,1.0
Hypertension,40000.0,NaN,NaN,NaN,0.505,0.499981,0.0,0.0,1.0,1.0,1.0
KidneyDisease,40000.0,NaN,NaN,NaN,0.5019,0.500003,0.0,0.0,1.0,1.0,1.0
StrokeHistory,40000.0,NaN,NaN,NaN,0.5017,0.500003,0.0,0.0,1.0,1.0,1.0
SystolicBP,40000.0,NaN,NaN,NaN,138.71025,27.646779,95.0,115.0,135.0,162.0,190.0
DiastolicBP,40000.0,NaN,NaN,NaN,87.581025,17.5712,60.0,72.0,85.0,103.0,120.0
RestingHR,40000.0,NaN,NaN,NaN,79.8429,17.558944,50.0,65.0,80.0,95.0,110.0
RespRate,40000.0,NaN,NaN,NaN,18.01035,3.736662,12.0,15.0,18.0,21.0,24.0
BodyTemp_C,40000.0,NaN,NaN,NaN,36.797695,0.405593,36.1,36.4,36.8,37.1,37.5
SpO2,40000.0,NaN,NaN,NaN,95.7502,2.939356,90.0,93.0,96.0,98.0,100.0
TotalChol,40000.0,NaN,NaN,NaN,222.755175,62.349095,120.0,171.0,216.0,275.0,340.0
HDL,40000.0,NaN,NaN,NaN,57.489875,19.089183,25.0,41.0,57.0,74.0,90.0
LDL,40000.0,NaN,NaN,NaN,135.149375,49.33149,50.0,93.0,135.0,178.0,220.0
Triglycerides,40000.0,NaN,NaN,NaN,199.710975,86.717603,50.0,125.0,200.0,274.0,350.0
FBS,40000.0,NaN,NaN,NaN,127.447225,44.569522,70.0,90.0,110.0,165.0,220.0
HbA1c,40000.0,NaN,NaN,NaN,6.97136,1.878933,4.5,5.4,6.3,8.5,11.0
Creatinine,40000.0,NaN,NaN,NaN,1.352253,0.490867,0.5,0.93,1.35,1.78,2.2
RestingECG,40000.0,NaN,NaN,NaN,1.002825,0.818189,0.0,0.0,1.0,2.0,2.0
ChestPainType,40000.0,NaN,NaN,NaN,1.497925,1.117286,0.0,0.0,1.0,2.0,3.0
ExerciseAngina,40000.0,NaN,NaN,NaN,0.2477,0.431682,0.0,0.0,0.0,0.0,1.0
MaxHR,40000.0,NaN,NaN,NaN,135.13265,38.009152,70.0,102.0,135.0,168.0,200.0
Oldpeak,40000.0,NaN,NaN,NaN,2.37529,1.709237,0.0,1.0,1.8,3.8,6.0
STSlope,40000.0,NaN,NaN,NaN,1.00075,0.817965,0.0,0.0,1.0,2.0,2.0
DailySteps,40000.0,NaN,NaN,NaN,8381.626075,5613.473308,500.0,3727.0,6683.5,13012.0,20000.0
HRV,40000.0,NaN,NaN,NaN,69.97825,29.216582,20.0,45.0,70.0,95.0,120.0
WearableECGAlerts,40000.0,NaN,NaN,NaN,7.5287,4.617603,0.0,4.0,7.0,12.0,15.0
MedicationAdherence,40000.0,NaN,NaN,NaN,74.965075,14.765941,50.0,62.0,75.0,88.0,100.0
RemoteMonitoringFreq,40000.0,NaN,NaN,NaN,14.965875,8.971116,0.0,7.0,15.0,23.0,30.0
AQIExposure,40000.0,NaN,NaN,NaN,154.539075,83.875479,10.0,82.0,154.0,227.0,300.0
AvgTempExposure,40000.0,NaN,NaN,NaN,25.029035,8.636031,10.0,17.6,25.1,32.5,40.0
HeartDisease,40000.0,NaN,NaN,NaN,0.5,0.500006,0.0,0.0,0.5,1.0,1.0

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
dupe_ids = df['Patient_ID'].duplicated().sum()
print("Duplicate Patient IDs:", dupe_ids) # reconfirmation of duplicate checking in patient id alone which is curical

Duplicate Patient IDs: 0

In [15]:
df.shape

(40000, 45)

# ***Data inconsistent***

In [16]:
invalid_age = df[(df['Age'] < 0) | (df['Age'] > 120)]
print("\nRows with invalid Age:", len(invalid_age)) #checking any invalid data in age column

Rows with invalid Age: 0

In [17]:
print("Gender values:", df['Gender'].unique()) #checking any spelling mistake in gender column

Gender values: ['Male' 'Female']

# ***Integrated with SQL***

In [18]:
!apt-get -y install postgresql postgresql-contrib > /dev/null
print("Done: PostgreSQL is installed")

Done: PostgreSQL is installed

In [19]:
!service postgresql start

 * Starting PostgreSQL 14 database server
   ...done.

In [20]:
!sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'mypassword';"
!sudo -u postgres psql -c "CREATE DATABASE heart_disease_db;"

print("Database 'heart_disease_db' ready")

ALTER ROLE
CREATE DATABASE
Database 'heart_disease_db' ready

In [21]:
!pip install psycopg2-binary sqlalchemy pandas -q

print("Libraries installed")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 69.3 MB/s eta 0:00:00
Libraries installed

In [22]:
from google.colab import files
from sqlalchemy import create_engine

In [23]:

engine = create_engine('postgresql://postgres:mypassword@localhost:5432/heart_disease_db')

In [24]:
df.to_sql('patients', engine, if_exists='replace', index=False)
print("Data loaded successfully into 'patients' table")

Data loaded successfully into 'patients' table

In [25]:
count = pd.read_sql("SELECT COUNT(*) FROM patients;", engine)
print(count)

   count
0  40000

In [26]:
result = pd.read_sql("select * from patients LIMIT 5;", engine)
print(result)

   Patient_ID  Age  Gender  Height_cm  Weight_kg   BMI  Waist_cm  Smoking  \
0           1   66    Male        175         86  28.1        73        0
1           2   48    Male        187         81  23.2       119        0
2           3   68    Male        181         71  21.7       123        1
3           4   41    Male        175         70  22.9       110        0
4           5   76  Female        156         75  30.8        78        0

   Alcohol  PhysicalActivity  ...  Oldpeak  STSlope  DailySteps  HRV  \
0        0                 0  ...      0.9        1       14313   73
1        1                 3  ...      1.0        1       15246   97
2        0                 0  ...      1.2        1       11572   41
3        1                 1  ...      1.4        0        8243  108
4        0                 4  ...      1.2        0       13219   34

   WearableECGAlerts  MedicationAdherence  RemoteMonitoringFreq  AQIExposure  \
0                  4                   84                     3          167
1                  2                   57                    16          224
2                  3                   81                     1          121
3                  1                   79                    28          296
4                 15                   79                    15          257

   AvgTempExposure  HeartDisease
0             26.8             0
1             14.9             0
2             33.0             0
3             21.8             0
4             19.4             0

[5 rows x 45 columns]

## ***SQL queries***

In [27]:
df.columns

Index(['Patient_ID', 'Age', 'Gender', 'Height_cm', 'Weight_kg', 'BMI',
       'Waist_cm', 'Smoking', 'Alcohol', 'PhysicalActivity', 'DietScore',
       'SleepHours', 'StressLevel', 'FamilyHistory', 'Diabetes',
       'Hypertension', 'KidneyDisease', 'StrokeHistory', 'SystolicBP',
       'DiastolicBP', 'RestingHR', 'RespRate', 'BodyTemp_C', 'SpO2',
       'TotalChol', 'HDL', 'LDL', 'Triglycerides', 'FBS', 'HbA1c',
       'Creatinine', 'RestingECG', 'ChestPainType', 'ExerciseAngina', 'MaxHR',
       'Oldpeak', 'STSlope', 'DailySteps', 'HRV', 'WearableECGAlerts',
       'MedicationAdherence', 'RemoteMonitoringFreq', 'AQIExposure',
       'AvgTempExposure', 'HeartDisease'],
      dtype='object')

In [28]:
query1 = """ SELECT "Patient_ID", "Age", "Gender", "HeartDisease" FROM patients WHERE "Age" > 60;"""

result1 = pd.read_sql(query1, engine)
print(result1.head(5))
print("Total patients over 60:", len(result1))

   Patient_ID  Age  Gender  HeartDisease
0           1   66    Male             0
1           3   68    Male             0
2           5   76  Female             0
3           9   78    Male             0
4          10   86    Male             0
Total patients over 60: 18206

In [29]:
query2 =""" SELECT "HeartDisease", COUNT(*) AS "total_patients", AVG("TotalChol") AS "avg_cholesterol" FROM patients GROUP BY "HeartDisease";"""
result2 = pd.read_sql(query2, engine)
print(result2)

   HeartDisease  total_patients  avg_cholesterol
0             0           20000        170.35900
1             1           20000        275.15135

In [30]:
query3 = """ SELECT "Patient_ID", "Age", CASE WHEN "Age" < 30 THEN 'Young'
WHEN "Age" BETWEEN 30 AND 60 THEN 'Middle-aged'
ELSE 'Senior' END AS "Age_group"
FROM patients LIMIT 10;"""

result3 = pd.read_sql(query3, engine)
print(result3)

   Patient_ID  Age    Age_group
0           1   66       Senior
1           2   48  Middle-aged
2           3   68       Senior
3           4   41  Middle-aged
4           5   76       Senior
5           6   43  Middle-aged
6           7   28        Young
7           8   35  Middle-aged
8           9   78       Senior
9          10   86       Senior

In [31]:
query4 = """ SELECT "Patient_ID", "Age", "TotalChol" FROM patients WHERE "TotalChol" > (SELECT AVG("TotalChol") FROM patients); """
result4 = pd.read_sql(query4, engine)
print(result4.head(5))
print("Patients with above-average cholesterol:", len(result4))

   Patient_ID  Age  TotalChol
0       20001   84        233
1       20002   67        272
2       20003   65        334
3       20004   26        234
4       20005   74        286
Patients with above-average cholesterol: 18012

# Supabase

postgresql://postgres.gxdzcmqvboxpwimxhvzg:[Karthick200025]@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres

In [32]:
supabase_engine = create_engine("postgresql://postgres.gxdzcmqvboxpwimxhvzg:Karthick200025@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres")

In [33]:
df.to_sql('patients', supabase_engine, if_exists='replace', index=False)
print("Data loaded into Supabase")

OperationalError: (psycopg2.OperationalError) connection to server at "aws-0-ap-southeast-1.pooler.supabase.com" (52.74.252.201), port 6543 failed: FATAL:  (ENOTFOUND) tenant/user postgres.gxdzcmqvboxpwimxhvzg not found
connection to server at "aws-0-ap-southeast-1.pooler.supabase.com" (52.74.252.201), port 6543 failed: FATAL:  (ENOTFOUND) tenant/user postgres.gxdzcmqvboxpwimxhvzg not found

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
dataset = pd.read_sql("SELECT COUNT(*) FROM patients;", supabase_engine)
print(dataset)

In [ ]:
test = pd.read_sql("SELECT * FROM patients LIMIT 5;", supabase_engine)
print(test)

In [ ]:
result1 = pd.read_sql("SELECT COUNT(*) FROM patients;", supabase_engine)
print(result1)

In [ ]:
new_data= pd.read_sql("SELECT * FROM patients;", supabase_engine)
print(result.shape)
print(result.head())

In [ ]:
new_data.to_csv('heart_disease_DV.csv', index=False)

In [ ]:
new_data.shape

In [ ]:
from google.colab import files
files.download('heart_disease_DV.csv')